import React from 'react';
import { AppStateProvider } from '../AppStateContext';
import { Inter } from 'next/font/google';
import './globals.css';

type Metadata = {
  title: string;
  description: string;
};

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AppStateProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </AppStateProvider>
  );
}